spring:
  mvc:
    #路径访问前缀
    static-path-pattern: /**
  resources:
    #静态资源目录
    #static-locations: [classpath:/mapper/]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.0.204:3306/blog?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 101.35.0.204
    port: 6379
    password: Lzy123456
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000
  #电子邮件
  mail:
    host: smtp.163.com
    username: iGuaDaOfficial@163.com
    password: KRIGODVMRPBKQJLC
    from: iGuaDaOfficial@163.com
    default-encoding: utf-8
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.nwpu.blog.bean
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #打印SQL语句
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8888
  servlet:
    context-path: /api
